### ISSUE TITLE
Lambda expressions are allowed only at source level 1.8 or above 	Multi-catch parameters are not allowed for source level below 1.7  	at net.minecraft.client.Minecraft.<init>(Minecraft.java:411) 	at net.minecraft.client.main.Main.main(Main.java:108) 	at Start.main(Start.java:7)

### ISSUE THREAD

**Issue by SpaceDevz** [OxideWaveLength/Minecraft-Hack-BaseClient#99] opened 2022-01-20 06:34 UTC
Lambda expressions are allowed only at source level 1.8 or above
	Multi-catch parameters are not allowed for source level below 1.7

	at net.minecraft.client.Minecraft.<init>(Minecraft.java:411)
	at net.minecraft.client.main.Main.main(Main.java:108)
	at Start.main(Start.java:7)

**Comment by OxideWaveLength** [comment] 2022-01-20 09:40
You have to set the Java version to 1.8 (Java 8) or higher.
Open Eclipse, right click the project, hover on "Build Path" and click on "Configure Build Path..."; click on "Libraries", double click on "JRE System Library" and set the "Execution environment" to Java 1.8
It's not a bug within the base client or a bug at all, it has to do with some programming instructions used to write the base client that have been added in Java 8 and are therefore not supported in prior versions

**Comment by OxideWaveLength** [comment] 2022-01-20 09:41
I will close the issue now; open it again if the issue isn't solved or if you need further assistance in applying the fix

**Closed** 2022-01-20 09:41 UTC
