### ISSUE TITLE
Fix Font

### ISSUE THREAD

**Issue by mymonsterdk** [OxideWaveLength/Minecraft-Hack-BaseClient#23] opened 2020-02-07 17:14 UTC
When you have maximized screen or fullscreen then the font on tabgui is fucked and not clear but in small window mode it is

**Comment by OxideWaveLength** [comment] 2020-02-07 19:58
I am aware of this issue, but unfortunately the problem is with the FontManager, which I did not make.
You can temporarily fix the issue by setting the Gui Scale in the Video Settings to "normal" (or "auto" if your screen is 1920x1080p)

![GuiScale](https://user-images.githubusercontent.com/60556091/74061576-9b9ba600-49ec-11ea-954f-83f2f310dba9.png)

**Comment by OxideWaveLength** [comment] 2020-04-03 21:09
Fixed in the commit ce7f451

**Closed by OxideWaveLength** 2020-04-03 21:09 UTC
Labels: bug
